import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { Compass, Menu, X, Moon, Sun } from 'lucide-react';
export const Navigation = ({ currentPage, onNavigate, onThemeToggle, darkMode }) => {
    const [mobileMenuOpen, setMobileMenuOpen] = React.useState(false);
    return (_jsx("nav", { className: "bg-white dark:bg-slate-800 border-b border-gray-200 dark:border-slate-700 sticky top-0 z-50", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4", children: [_jsxs("div", { className: "flex justify-between items-center h-16", children: [_jsxs("button", { onClick: () => onNavigate({ type: 'dashboard' }), className: "flex items-center gap-2 hover:opacity-80 transition-opacity", children: [_jsx("div", { className: "w-10 h-10 bg-gradient-to-br from-indigo-600 to-purple-600 rounded-lg flex items-center justify-center", children: _jsx(Compass, { size: 24, className: "text-white" }) }), _jsx("span", { className: "font-bold text-lg hidden sm:inline text-gray-900 dark:text-white", children: "DIP" })] }), _jsx("div", { className: "hidden md:flex items-center gap-8", children: _jsx("button", { onClick: () => onNavigate({ type: 'dashboard' }), className: `px-3 py-2 rounded-lg transition-colors ${currentPage.type === 'dashboard'
                                    ? 'bg-indigo-100 dark:bg-indigo-900 text-indigo-900 dark:text-indigo-100 font-medium'
                                    : 'text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-slate-700'}`, children: "Dashboard" }) }), _jsxs("div", { className: "flex items-center gap-4", children: [_jsx("button", { onClick: onThemeToggle, className: "p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-slate-700 transition-colors", "aria-label": "Toggle theme", children: darkMode ? (_jsx(Sun, { size: 20, className: "text-yellow-500" })) : (_jsx(Moon, { size: 20, className: "text-gray-700" })) }), _jsx("button", { onClick: () => setMobileMenuOpen(!mobileMenuOpen), className: "md:hidden p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-slate-700", children: mobileMenuOpen ? _jsx(X, { size: 20 }) : _jsx(Menu, { size: 20 }) })] })] }), mobileMenuOpen && (_jsx("div", { className: "md:hidden border-t py-4", children: _jsx("button", { onClick: () => {
                            onNavigate({ type: 'dashboard' });
                            setMobileMenuOpen(false);
                        }, className: "block w-full text-left px-4 py-2 rounded-lg hover:bg-gray-100 dark:hover:bg-slate-700", children: "Dashboard" }) }))] }) }));
};
